"""empty message

Revision ID: 019332189b97
Revises: 4dba02080ab9
Create Date: 2021-06-12 15:37:30.876920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019332189b97'
down_revision = '4dba02080ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('organization',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=150), nullable=True),
    # sa.Column('address', sa.String(length=150), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name')
    # )
    # op.add_column('location', sa.Column('name', sa.String(length=150), nullable=True))
    op.add_column('location', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'location', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'organization_id')
    op.drop_column('location', 'name')
    op.drop_table('organization')
    # ### end Alembic commands ###
