"""Added is_admin column

Revision ID: 0fbb44492c19
Revises: dd0da8db1ff5
Create Date: 2024-06-05 21:22:38.255170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbb44492c19'
down_revision = 'dd0da8db1ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location_organization_id_fkey', 'location', type_='foreignkey')
    op.drop_column('location', 'organization_id')
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_constraint('user_organization_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_organization_id_fkey', 'user', 'organization', ['organization_id'], ['id'])
    op.drop_column('user', 'is_admin')
    op.add_column('location', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('location_organization_id_fkey', 'location', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###
