"""delete state column

Revision ID: 258362e670e6
Revises: ee635aa5e335
Create Date: 2022-09-12 20:28:50.970241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258362e670e6'
down_revision = 'ee635aa5e335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organization_state_key', 'organization', type_='unique')
    op.drop_column('organization', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('state', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.create_unique_constraint('organization_state_key', 'organization', ['state'])
    # ### end Alembic commands ###
