"""added user_id foreign key to location table

Revision ID: 44c759c1f131
Revises: 0fbb44492c19
Create Date: 2024-06-05 21:53:56.138510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c759c1f131'
down_revision = '0fbb44492c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    op.add_column('location', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'location', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'user_id')
    op.create_table('organization',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='organization_pkey'),
    sa.UniqueConstraint('name', name='organization_name_key')
    )
    # ### end Alembic commands ###
