"""empty message

Revision ID: 698f01f2289e
Revises: 519c59124887
Create Date: 2024-06-11 15:50:56.310068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698f01f2289e'
down_revision = '519c59124887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('pantry_fullness', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('photo', sa.String(length=150), nullable=True))
    op.add_column('report', sa.Column('description', sa.String(length=250), nullable=True))
    op.drop_column('report', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('status', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('report', 'description')
    op.drop_column('report', 'photo')
    op.drop_column('report', 'pantry_fullness')
    # ### end Alembic commands ###
