"""empty message

Revision ID: 6b5988b1ac1c
Revises: 9922a3921924
Create Date: 2024-06-11 16:30:18.259880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5988b1ac1c'
down_revision = '9922a3921924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'test')
    # ### end Alembic commands ###
