"""add unsubscribe_token to notification table

Revision ID: 8551925f3652
Revises: 2e403d74a537
Create Date: 2025-07-01 22:17:04.236071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8551925f3652'
down_revision = '2e403d74a537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('unsubscribe_token', sa.String(length=100), nullable=True))
    op.add_column('notification', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'notification', ['unsubscribe_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='unique')
    op.drop_column('notification', 'created_at')
    op.drop_column('notification', 'unsubscribe_token')
    # ### end Alembic commands ###
