"""empty message

Revision ID: 855d05c3a7dd
Revises: 2201116989f9
Create Date: 2021-07-09 17:32:39.752188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855d05c3a7dd'
down_revision = '2201116989f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('test', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'test')
    # ### end Alembic commands ###
