"""added age and is_owner columns to User table

Revision ID: 8614b77187c2
Revises: 44c759c1f131
Create Date: 2024-06-09 15:32:38.599512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8614b77187c2'
down_revision = '44c759c1f131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    op.drop_constraint('location_user_id_fkey', 'location', type_='foreignkey')
    op.drop_column('location', 'user_id')
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_owner', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_owner')
    op.drop_column('user', 'age')
    op.add_column('location', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('location_user_id_fkey', 'location', 'user', ['user_id'], ['id'])
    op.create_table('organization',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='organization_pkey'),
    sa.UniqueConstraint('name', name='organization_name_key')
    )
    # ### end Alembic commands ###
