"""added points column to report table

Revision ID: 96bc0628833e
Revises: ee43e934a76a
Create Date: 2024-06-13 21:59:47.331771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96bc0628833e'
down_revision = 'ee43e934a76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'points')
    # ### end Alembic commands ###
