"""temporarily add test column to location to change foreign key

Revision ID: 9922a3921924
Revises: 698f01f2289e
Create Date: 2024-06-11 16:28:00.967821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9922a3921924'
down_revision = '698f01f2289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('test', sa.Integer(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'test')
    # ### end Alembic commands ###
