"""added low_inventory and new_location columns to notification table

Revision ID: a4fea2cea4b7
Revises: 96bc0628833e
Create Date: 2024-06-14 18:24:50.028564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fea2cea4b7'
down_revision = '96bc0628833e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('low_inventory', sa.Boolean(), nullable=True))
    op.add_column('notification', sa.Column('new_location', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'new_location')
    op.drop_column('notification', 'low_inventory')
    # ### end Alembic commands ###
