"""Add vision_analysis field to Report model

Revision ID: a5ebe9fafb45
Revises: e05cb535ae76
Create Date: 2025-06-26 20:51:11.192629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ebe9fafb45'
down_revision = 'e05cb535ae76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('vision_analysis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'vision_analysis')
    # ### end Alembic commands ###
