"""added nullable to optional fields

Revision ID: ee1c53aea71a
Revises: 4892f5d4ef37
Create Date: 2024-06-16 20:15:04.309878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1c53aea71a'
down_revision = '4892f5d4ef37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'new_location')
    op.drop_column('report', 'points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('new_location', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
