"""removed test column

Revision ID: ee43e934a76a
Revises: 6b5988b1ac1c
Create Date: 2024-06-11 16:34:13.415213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee43e934a76a'
down_revision = '6b5988b1ac1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
