"""Added user_id column to location table

Revision ID: efc641bfe07c
Revises: f2291aa7876d
Create Date: 2024-06-09 17:09:12.547839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc641bfe07c'
down_revision = 'f2291aa7876d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'location', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'user_id')
    # ### end Alembic commands ###
