"""empty message

Revision ID: f2291aa7876d
Revises: 8614b77187c2
Create Date: 2024-06-09 16:46:53.870978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2291aa7876d'
down_revision = '8614b77187c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.String(length=150), nullable=True))
    op.drop_column('user', 'is_owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_owner', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
